version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mevimensagerdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./Back-End
    volumes:
      - ./Back-End:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_NAME=mevimensagerdb
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432

  frontend:
    build: "./Front-End Web"
    volumes:
      - "./Front-End Web:/app"
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
